language: bash
services: docker

env:
  - VERSION=latest
  - VERSION=headless

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - test latest = "$VERSION" || cd "$VERSION"
  - image="marceloalmeida/docker-jenkins-dind-slave:${VERSION}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
